# Generated by Django 3.2.9 on 2022-01-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=300)),
                ('eno', models.IntegerField()),
                ('esal', models.IntegerField()),
                ('eaddr', models.CharField(max_length=300)),
            ],
        ),
    ]
